### ISSUE TITLE
{TIMESTAMP}, {ITEM} placeholders not working

### ISSUE THREAD

**Issue by TheKingElessar** [evancolewright/HeadDrops#3]
The `{TIMESTAMP}` and `{ITEM}` placeholders aren't working for me. This is all that HeadDrops logs:

```
[21:10:37 INFO]: [HeadDrops] Enabling HeadDrops v1.2-SNAPSHOT
[21:10:37 INFO]: [HeadDrops] Found minor version: 18 (v1_18_R1)
```

This is my full `config.yml`:

```
default_drop_chance: 0.5
slain_drop_chance: 1.0

default_head:
  enabled: true
  name: "&4&l{PLAYER}'s &f&lHead"
  lore:
    - "&fDied on &0{TIMESTAMP}"

slain_head:
  enabled: true
  name: "&4&l{PLAYER}'s &f&lHead"
  # If the player is killed by a player that used their fist, what should the {ITEM} placeholder be replaced with?
  fist_text: "their bare hands"
  lore:
    - "&fKilled by &1&l{KILLER}"
    - "&fon &0{TIMESTAMP}"
    - "&fwith &0{ITEM}"
```

![image](https://user-images.githubusercontent.com/46632454/149593899-37e3f6e9-2e50-423a-bda5-36d300f1a399.png)
![image](https://user-images.githubusercontent.com/46632454/149594726-6007b060-82f9-46b8-94c5-41ac18490044.png)

Do you know what the issue is?
